# Generated by Django 4.2.4 on 2023-10-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('k', 'KARACHI'), ('B', 'Bahalwalpur'), ('hsl', 'hasilpur'), ('jmpr', 'jamalpur')], max_length=20),
        ),
    ]
