# Generated by Django 4.2.4 on 2023-11-26 04:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_app', '0004_rename_categories_categories1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories1',
            new_name='Category1',
        ),
    ]
